# Title of the page
title: "Sof's life"
# Your name
author: Sofía Saulés
# Show a link to LinkedIn in the header intro. Comment out to disable.
# linkedin: 
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
 url: https://neil.gg
  title: neil.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - Noviembre 1992: "Nací en la, no tan concurrida hasta el momento, CDMX, antes DF."
    - Marzo 1994: "Nació mi compañerito de aventuras y de la vida, mi hermano."
    - Agosto 1999: "Entré a la primaria, un niño me preguntó en qué año había nacido, le dije que en 1998 y se burló de mí. Fue la primera vez que sentí vergüenza, no sabía nada de la vida ni de fechas."
  - name: 2000's
   - events:
    - Abril 2004: "Una niña se burló del color de mi piel. El bullying de la primaria... sin duda es uno de los que más secuelas deja"
    - Diciembre 2005: "Falleció el hermano de mi mamá, tenía 30 años. Comprendí lo finita que era la vida."
    - Agosto 2008: "Entré a la preparatoria, mi primer logro. Mi prima no se quedó entonces en la familia optaron por no felicitarme o hacerlo en "secreto"."
 
  - name: 2010's
    events:
    - Agosto 2011: "Entré a la Universidad a estudiar Biología, aunque yo quería estudiar Letras. En realidad estaba indecisa."
    - Diciembre 2012: "Tuve mi primera relación significativa, creí que ahí iba a estar por siempre, pero sólo fueron cuatro años y medio."
    - Julio 2016: "Falleció mi abuelo, el padre de mi padre. Qué dificil es perder a alguien a quien siempre vas a querer y nunca pudiste abrazar"
    - Febrero 2017: "Competí en mi primer triatlón, ni siquiera sabía usar los cambios de la bicicleta. El deporte comenzaba a ser una prioridad en mi vida."
    - Noviembre 2017: "Me titulé. Ya quería cerrar ese ciclo"
    - Junio 2019: "Me independicé, me salí de la casa de mis padres para juntarme con mi pareja de ese momento. No resultó bien, pero tampoco regresé al nido."
    - Julio 2019: "Corrí mi primer medio maratón"
  
  - name: 2020's
    events:
    - Julio 2020: "Vivir en medio de una pandemia"
    - Agosto 2022: "Me resbalé y me rompí un ligamento de la rodilla, me tuvieron que operar. Estuve sin caminar más de dos meses, más la rehabilitación."
    - Abril 2023: "Entré a estudiar a Laboratoria. Emocionada por este nuevo comienzo."
